# constants.py

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60

LINE_WIDTH = 2

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 180          # degrees per second
PLAYER_MOVE_SPEED = 300          # px/sec

# Shooting
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500         # px/sec
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

# Asteroids
ASTEROID_MIN_RADIUS = 15
ASTEROID_MAX_RADIUS = 60
ASTEROID_KINDS = ASTEROID_MAX_RADIUS // ASTEROID_MIN_RADIUS
ASTEROID_SPAWN_RATE_SECONDS = 1.0
